site_name: HPRC Wiki
site_url: https://docs.ncsurocketry.org/

docs_dir: docs

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.indexes
    - content.code.copy
    - content.action.edit
    - search.suggest
    - search.highlight
  palette: 
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

nav:
  - Home: index.md
  - Rocketry 101:
      - Getting Started: rocketry-101/getting-started.md
      - Recovery: rocketry-101/deployment.md
      - Stability: rocketry-101/stability.md
      - Motors: rocketry-101/motors.md
      - Certifications: 
          - Overview: rocketry-101/certs/certifications.md
          - Level 1: rocketry-101/certs/level-1.md
          - Level 2: rocketry-101/certs/level-2.md
          - Level 3: rocketry-101/certs/level-3.md
      - Simulations: rocketry-101/simulations.md
      - Staging: rocketry-101/staging.md
      - Aerodynamics: rocketry-101/aerodynamics.md
  - Safety:
      - Safety Overview: safety/safety.md
      - Ejection Testing: safety/ejection-testing.md
  - Recovery:
      - Altimeters: 
          - Overview: recovery/altimeters/altimeters.md
          - Guides:
              - Stratologger: recovery/altimeters/use/stratologger.md          
              - Fluctus: recovery/altimeters/use/fluctus.md
              - EasyMini: recovery/altimeters/use/easymini.md
              - MissleWorks:
                  - RRC3 Sport: recovery/altimeters/use/missleworks/rrc3.md
                  - RRC2+: recovery/altimeters/use/missleworks/rrc2.md
              - Eggtimers:
                  - Quasar: recovery/altimeters/use/eggtimers/quasar.md
                  - Quantum: recovery/altimeters/use/eggtimers/quantum.md
                  - Quark: recovery/altimeters/use/eggtimers/quark.md
          - Altimeter Testing: recovery/altimeters/testing.md
      - Tracking:
          - Overview: recovery/tracking.md
          - GPS Trackers: recovery/tracking/gps-trackers.md
          - RF Trackers: recovery/tracking/rf-trackers.md
      - Deployment: recovery/deployment.md          
  - Vehicle:
    - Composites: composites.md
  - Payload:
    - Past Payloads: payload/payload.md
    - Raspberry Pi: payload/raspberry-pi.md
    - Cameras: payload/cameras.md
  - The Lab:
    - About The Lab: lab/lab.md
    - Tool Safety: lab/tools.md
    - 3D Printing: lab/3d-printing.md
    - Soldering: lab/soldering.md
    - Hazard Storage and Disposal: lab/hazard-storage.md
      

extra_css:
  - extra.css

plugins:
  - glightbox
  - search

markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
