site_name: HPRC Documentation
site_url: https://docs.ncsurocketry.org/

docs_dir: docs

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.indexes
    - content.code.copy
    - content.action.edit
    - search.suggest
    - search.highlight

nav:
  - Home: index.md
  - Safety: safety.md
  - Recovery: recovery.md

extra_css:
  - extra.css
